# Generated by Django 4.2.7 on 2023-11-27 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('product', '0002_chaptermodel_productmodel_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaptermodel',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
    ]
