# Generated by Django 4.2.7 on 2023-11-28 07:43

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('product', '0003_chaptermodel_site'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='chaptermodel',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager('site')),
            ],
        ),
        migrations.AddField(
            model_name='productmodel',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='site',
            field=models.ManyToManyField(to='sites.site'),
        ),
    ]
