# Generated by Django 4.2.7 on 2023-12-01 09:27

from django.db import migrations
import django.db.models.manager
import product.models.product


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_chaptermodel_managers_productmodel_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='productmodel',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', product.models.product.CustomSiteManager()),
            ],
        ),
    ]
