# Generated by Django 4.2.7 on 2023-12-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productmodel_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaptermodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_chapter/'),
        ),
    ]
