# Generated by Django 4.2.7 on 2023-11-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HitCount',
            fields=[
                ('path', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('hits', models.IntegerField(default=0)),
            ],
        ),
    ]
